spring:
  application:
    name: comfama-reto-api
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    com.comfama: DEBUG
reto: