spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: comfama-reto-api
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    name: comfama-reto-api
    initialization-mode: always
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dbcomfamadigitaldev.csfppvl3wg8f.us-east-1.rds.amazonaws.com/RetoComfama?serverTimezone=America/Bogota
    username: admin
    password: e~-}+T=3tc
server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    com.comfama: DEBUG
reto: