spring:
  application:
    name: archetype-api
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    name: archetype-microservice
    url: jdbc:h2:file:./build/h2db/db/archetype-microservice;DB_CLOSE_DELAY=-1
  rabbitmq:
    host: localhost
    port: 5672
    connection-timeout: 6000

server:
  port: 7000
  servlet:
    context-path: /archetype
logging:
  level:
    com.comfama: DEBUG
archetype: