---
kind: Service
apiVersion: v1
metadata:
  name: comfama-archetype-api
  namespace: master
  labels:
    app: comfama-archetype-api
spec:
  selector:
    app: comfama-archetype-api
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 7000
    targetPort: 7000