---
kind: Service
apiVersion: v1
metadata:
  name: comfama-reto-api
  namespace: master
  labels:
    app: comfama-reto-api
spec:
  selector:
    app: comfama-reto-api
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 7000
    targetPort: 7000